apps/board/models.py
from apps.app import db
from apps.auth.models import User

class Board(db.Model):
    __tablename__ = "board"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('userinfo.id', ondelete='CASCADE'), nullable=True, server_default='1')
    user = db.relationship('User', backref=db.backref('board_set'))

class Answer(db.Model):
    __tablename__ = "answer"
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('userinfo.id', ondelete='CASCADE'), nullable=True, server_default='1')
    user = db.relationship('User', backref=db.backref('answer_set'))
    board_id = db.Column(db.Integer, db.ForeignKey('board.id', ondelete='CASCADE'), nullable=True, server_default='1')
    board = db.relationship('Board', backref=db.backref('answer_set'))

apps/board/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo

class BoardForm(FlaskForm):
    title = StringField(
        "제목",
        validators=[
            DataRequired(message="제목은 필수입니다."),
            Length(1, 30, message="30문자 이내로 입력해 주세요."),
        ],
    )

    content = StringField(
        "내용",
        validators=[
            DataRequired(message="내용은 필수입니다."),
            Length(1, 500, message="500문자 이내로 입력해 주세요."),
        ],
    )

    submit = SubmitField("등록")

class AnswerForm(FlaskForm):
    content = StringField(
        "내용",
        validators=[
            DataRequired(message="내용은 필수입니다."),
            Length(1, 500, message="500문자 이내로 입력해 주세요."),
        ],
    )

    submit = SubmitField("등록")

apps/board/views.py
from flask import Blueprint, render_template, redirect, url_for, session, g, flash, request
from apps.board.models import Board, Answer
from apps.board.forms import BoardForm, AnswerForm
from apps.app import db
import datetime
from sqlalchemy import exc
board = Blueprint("board",
                 __name__,
                 template_folder="templates",
                 static_folder="static",
                 )

@board.route("/")
def index():
    board_list = Board.query.order_by(Board.create_date.desc()).all()
    return render_template("board/index.html", board_list=board_list)


@board.route("/new", methods=["get","post"])
def create_board():
    user = g.user

    if user == None:
        flash("로그인 상태가 아닙니다.")
        return redirect(url_for('auth.login'))
    form = BoardForm()
    if form.validate_on_submit():
        board = Board(title = form.title.data, content = form.content.data, user_id = user.id, create_date = datetime.datetime.now())
        try:
            db.session.add(board)
            db.session.commit()
        except exc.IntegrityError as error:
            flash('MySQL error: {}'.format(error))
            return redirect(url_for("board.create_board"))
        return redirect(url_for('board.index'))

    return render_template("board/create.html",form=form)


@board.route("/detail/<board_id>", methods=["get", "post"])
def detail_board(board_id):
    board = Board.query.filter_by(id=board_id).first()
    form = AnswerForm()

    return render_template("board/detail.html",board = board, form=form)


@board.route("/edit/<board_id>", methods=['get', 'post'])
def edit_board(board_id):
    board = Board.query.filter_by(id=board_id).first()
    user = g.user

    if user == None:
        flash("로그인 상태가 아닙니다.")
        return redirect(url_for('auth.login'))
    elif board == None:
        flash("글이 존재하지 않습니다.")
        return redirect(url_for('board.index'))
    elif user.id != board.user_id:
        flash("글쓴이가 아닙니다.")
        return redirect(url_for('board.index'))
    
    form = BoardForm()
    if request.method == 'GET': 
        form.title.data = board.title
        form.content.data = board.content
    if form.validate_on_submit():
        board.title = form.title.data
        board.content = form.content.data
        try:
            db.session.add(board)
            db.session.commit()
        except exc.IntegrityError as error:
            flash('MySQL error: {}'.format(error))
            return redirect(url_for("board.edit_board"))
        return redirect(url_for('board.index'))

    return render_template('board/edit.html',form=form, board=board)

@board.route("delete/<board_id>", methods=['get'])
def delete_board(board_id):
    board = Board.query.filter_by(id=board_id).first()
    user = g.user

    if user == None:
        flash("로그인 상태가 아닙니다.")
        return redirect(url_for('auth.login'))
    elif board == None:
        flash("글이 존재하지 않습니다.")
        return redirect(url_for('board.index'))
    elif user.id != board.user_id:
        flash("글쓴이가 아닙니다.")
        return redirect(url_for('board.index'))
    try:
        db.session.delete(board)
        db.session.commit()
    except exc.IntegrityError as error:
        flash('MySQL error: {}'.format(error))
        return redirect(url_for("board.edit_board"))

    return redirect(url_for('board.index'))

@board.route("/detail/<board_id>/answer", methods=['post'])
def create_answer(board_id):
    user = g.user
    board = Board.query.filter_by(id=board_id).first()

    if user == None:
        flash("로그인 상태가 아닙니다.")
        return redirect(url_for('auth.login'))
    elif board == None:
        flash("글이 존재하지 않습니다.")
        return redirect(url_for('board.index'))
    form = AnswerForm()
    if form.validate_on_submit():
        answer = Answer(content = form.content.data, user_id = user.id, board_id = board.id ,create_date = datetime.datetime.now())
        try:
            db.session.add(answer)
            db.session.commit()
        except exc.IntegrityError as error:
            flash('MySQL error: {}'.format(error))
            return redirect(url_for("board.detail_board",board_id=board.id))
    return redirect(url_for('board.detail_board',board_id=board.id))

@board.route("/detail/<board_id>/answer/<answer_id>/delete", methods=['get'])
def delete_answer(board_id, answer_id):
    board = Board.query.filter_by(id=board_id).first()
    user = g.user
    answer = Answer.query.filter_by(id=answer_id, user=user, board=board).first()
    if user == None:
        flash("로그인 상태가 아닙니다.")
        return redirect(url_for('auth.login'))
    elif board == None:
        flash("글이 존재하지 않습니다.")
        return redirect(url_for('board.index'))
    elif user.id != answer.user_id:
        flash("글쓴이가 아닙니다.")
        return redirect(url_for('board.index'))
    try:
        db.session.delete(answer)
        db.session.commit()
    except exc.IntegrityError as error:
        flash('MySQL error: {}'.format(error))
        redirect(url_for('board.detail_board',board_id=board.id))

    return redirect(url_for('board.detail_board',board_id=board.id))

apps/board/templates/board/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">

</head>
<body>
    <!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('board.index') }}">게시판</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('board.create_board') }}">글쓰기</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>
    {% block content %}
    {% endblock %}
</body>
</html>

apps/board/templates/board/create.html
{% extends 'board/base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시판 글쓰기</h5>
    <form method="post" class="my-3">
        {% include "board/form_errors.html" %}
        {{ form.csrf_token }}
        <div class="mb-3">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ form.title.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10" value="{{ form.content.data or '' }}" ></textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

apps/board/templates/board/detail.html
{% extends "board/base.html" %}
{% block content %}

<div class="container my-3">
    <!-- 게시글 내용 -->
    <h2 class="border-bottom py-2">{{ board.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ board.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ board.create_date }}
                </div>
            </div>
            <div class="my-3">
                {% if g.user == board.user %}
                <a href="{{ url_for('board.edit_board', board_id=board.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 목록 -->
    <h5 class="border-bottom my-3 py-2">{{ board.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in board.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
            <div class="my-3">
                {% if g.user == answer.user %}
                <a href="{{ url_for('board.delete_answer', board_id=board.id,answer_id=answer.id) }}"
                   class="btn btn-sm btn-outline-secondary">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{{ url_for('board.create_answer', board_id=board.id) }}" method="post" class="my-3">
        {% include "board/form_errors.html" %}
        {{ form.csrf_token }}
        <div class="mb-3">
            <textarea name="content" id="content" class="form-control" rows="3"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

apps/board/templates/board/edit.html
{% extends 'board/base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시판 글수정</h5>
    <form action="{{url_for('board.edit_board',board_id=board.id)}}" method="post" class="my-3">
        {% include "board/form_errors.html" %}
        {{ form.csrf_token }}
        <div class="mb-3">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ form.title.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">수정하기</button>
    </form>
    <div class="my-3">
        {% if g.user == board.user %}
        <a href="{{ url_for('board.delete_board', board_id=board.id) }}"
           class="btn btn-primary">삭제</a>
        {% endif %}
    </div>
</div>
{% endblock %}

apps/board/templates/board/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

apps/board/templates/board/index.html
{% extends "board/base.html" %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if board_list %}
        {% for board in board_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{url_for('board.detail_board', board_id = board.id)}}">{{ board.title }}</a>
            </td>
            <td>{{ board.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}